language: python
python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "nightly"

sudo: false
os:
- linux

env:
- CC=clang
- CC=gcc CFLAGS="--coverage -O0"

install:
- pip install -U pip
- pip install hypothesis hypothesis-pytest codecov
- python setup.py build_ext --inplace

before_script:
- python patch_doctest.py

script:
- python -m doctest fastnumbers*.so
- (test "$TRAVIS_PYTHON_VERSION" != '2.6' && python -m pytest --doctest-glob=README.rst) || echo "skipping pytest on Python 2.6"

after_success:
- (test "$CC" == "gcc" && codecov --gcov-args "-o ${PWD}") || echo "skipping coverage for $CC"
