language: python
sudo: false
os:
- linux
env:
- CC=clang
- CC=gcc
python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "nightly"
install:
- pip install -U pip
- pip install hypothesis hypothesis-pytest
- pip install -e .
before_script:
- python patch_doctest.py
script:
- python -m doctest fastnumbers*.so
- if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python -m pytest --doctest-glob=README.rst; fi
