language: python
os:
- linux
- osx
python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
install:
- pip install -e .
before_script:
- python patch_doctest.py
script:
- python -m doctest fastnumbers*.so
- python -m pytest --doctest-glob=README.rst
