language: python
python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "nightly"

sudo: false
os:
- linux

addons:
  apt:
    packages:
    - lcov

env:
- CC=clang
- CC=gcc

install:
- pip install -U pip
- pip install hypothesis hypothesis-pytest codecov
- CFLAGS="-coverage" pip install -e .

before_script:
- python patch_doctest.py

script:
- python -m doctest fastnumbers*.so
- if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then python -m pytest --doctest-glob=README.rst; fi

after_success:
- lcov --capture --directory . --output-file lcov.info
- codecov
